using System.Text;
using RoboCopyGUI.Models;

namespace RoboCopyGUI.Services;

public sealed class BatchScriptExporter
{
    public async Task ExportBatAsync(IEnumerable<CopyTask> tasks, string filePath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("REM ═══════════════════════════════════════════════════════");
        sb.AppendLine("REM Generated by RoboCopy GUI");
        sb.AppendLine($"REM Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("REM ═══════════════════════════════════════════════════════");
        sb.AppendLine();
        sb.AppendLine("setlocal enabledelayedexpansion");
        sb.AppendLine("set ERROR_COUNT=0");
        sb.AppendLine();

        int index = 1;
        foreach (var task in tasks)
        {
            var args = task.Options.BuildArguments();
            sb.AppendLine($"REM ── Task {index}: {task.Source} → {task.Destination} ──");
            sb.AppendLine($"echo [{index}] Copying: {task.Source}");
            sb.AppendLine($"echo        To:      {task.Destination}");
            sb.AppendLine($"robocopy \"{task.Source}\" \"{task.Destination}\" {args}");
            sb.AppendLine("set TASK_EXIT=%ERRORLEVEL%");
            sb.AppendLine("if !TASK_EXIT! GEQ 8 (");
            sb.AppendLine("    echo [ERROR] Task {index} failed with exit code !TASK_EXIT!");
            sb.AppendLine("    set /a ERROR_COUNT+=1");
            sb.AppendLine(") else (");
            sb.AppendLine("    echo [OK] Task {index} completed with exit code !TASK_EXIT!");
            sb.AppendLine(")");
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("echo ═══════════════════════════════════════════════════════");
        sb.AppendLine("echo All tasks completed. Errors: !ERROR_COUNT!");
        sb.AppendLine("if !ERROR_COUNT! GTR 0 (");
        sb.AppendLine("    echo WARNING: Some tasks had errors.");
        sb.AppendLine("    exit /b 1");
        sb.AppendLine(")");
        sb.AppendLine("pause");

        await File.WriteAllTextAsync(filePath, sb.ToString(), Encoding.UTF8);
    }

    public async Task ExportPowerShellAsync(IEnumerable<CopyTask> tasks, string filePath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ═══════════════════════════════════════════════════════");
        sb.AppendLine("# Generated by RoboCopy GUI");
        sb.AppendLine($"# Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("# ═══════════════════════════════════════════════════════");
        sb.AppendLine();
        sb.AppendLine("$ErrorActionPreference = 'Continue'");
        sb.AppendLine("$totalErrors = 0");
        sb.AppendLine();

        int index = 1;
        foreach (var task in tasks)
        {
            var args = task.Options.BuildArguments();
            sb.AppendLine($"# ── Task {index}: {task.Source} → {task.Destination} ──");
            sb.AppendLine($"Write-Host \"[{index}] Copying: {task.Source}\" -ForegroundColor Cyan");
            sb.AppendLine($"robocopy \"{task.Source}\" \"{task.Destination}\" {args}");
            sb.AppendLine("$exitCode = $LASTEXITCODE");
            sb.AppendLine("if ($exitCode -ge 8) {");
            sb.AppendLine($"    Write-Host \"[ERROR] Task {index} failed with exit code $exitCode\" -ForegroundColor Red");
            sb.AppendLine("    $totalErrors++");
            sb.AppendLine("} else {");
            sb.AppendLine($"    Write-Host \"[OK] Task {index} completed with exit code $exitCode\" -ForegroundColor Green");
            sb.AppendLine("}");
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("Write-Host '═══════════════════════════════════════════════════════' -ForegroundColor Yellow");
        sb.AppendLine("Write-Host \"All tasks completed. Errors: $totalErrors\" -ForegroundColor $(if ($totalErrors -gt 0) {'Red'} else {'Green'})");
        sb.AppendLine("if ($totalErrors -gt 0) { exit 1 }");
        sb.AppendLine("Read-Host 'Press Enter to exit'");

        await File.WriteAllTextAsync(filePath, sb.ToString(), Encoding.UTF8);
    }

    public string GeneratePreview(IEnumerable<CopyTask> tasks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("@echo off");
        sb.AppendLine("REM Generated by RoboCopy GUI");
        sb.AppendLine();

        foreach (var task in tasks)
        {
            var args = task.Options.BuildArguments();
            sb.AppendLine($"robocopy \"{task.Source}\" \"{task.Destination}\" {args}");
        }

        return sb.ToString();
    }
}
